= Example: Working With Throwables
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Java, Throwable, error



The Java module exposes useful DataWeave functions to deal with Throwable instances.

IMPORTANT: These have been available since version 1.2.0.

== Checking for a Cause

You can check whether a Throwable was caused by a certain type of Exception using the `isCausedBy` function.
This is specially useful for adding logic to
https://docs.mulesoft.com/mule-runtime/4.1/intro-error-handlers#error-handlers[error handlers].

Suppose we have the following Java class:

[source,java,linenums]
----
package com.foo;

public class TaxCalculator {

	public Double calculateTax(Double price) {
		if (price == null) {
			throw new NullPointerException("Must provide a value for price");
		}
		if (price < 0) {
			throw new IllegalArgumentException("Price must be a non-negative value, but was: " + price);
		}
		return price * 0.21;
	}

}
----

As we can see, the _calculateTax(Double price)_ method declares 2 different type of exceptions:
IllegalArgumentException and NullPointerException. Suppose that the code below is part of a
flow and that we can get an error during the execution of the
xref:java/java-invoke-method.adoc[`invoke` operation].
If we want to check which of the Java exceptions occurred during the failed invocation of
the _calculateTax(Double price)_ method, we can use the `isCausedBy` function in our error
handler and add different logic for each of the cases.

[source,xml,linenums]
----
<java:new class="com.foo.TaxCalculator" constructor="TaxCalculator()" target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]" class="com.foo.TaxCalculator" method="calculateTax(Double)">
    <java:args>#[{price: payload.price}]</java:args>
</java:invoke>
<error-handler>
    <on-error-continue when="#[Java::isCausedBy(error.cause, 'java.lang.IllegalArgumentException')]">
        <set-payload value="You can't have negative prices."/>
    </on-error-continue>
    <on-error-continue type="#[Java::isCausedBy(error.cause, 'java.lang.NullPointerException')]">
        <set-payload value="There is no price."/>
    </on-error-continue>
</error-handler>
----

== Obtaining a Root Cause

You can also obtain the root cause of a Throwable, disregarding any exception wrapping, with the `getRootCause` function.

In the following example, all tax calculation errors are handled by another class,
which takes the root cause of the Throwable. So we use the `getRootCause` function to
pass the root cause as an argument to the _handle(Throwable)_ method.

[source,xml,linenums]
----
<java:new class="com.foo.TaxCalculator"
  constructor="TaxCalculator()"
  target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]"
  class="com.foo.TaxCalculator"
  method="calculateTax(Double)">
    <java:args>#[{price: payload.price}]</java:args>
</java:invoke>
<error-handler>
    <on-error-continue>
      <java:invoke-static class="com.foo.FailureHandler" method="handle(Throwable)">
          <java:args>#[{cause: Java::getRootCause(error.cause)}]</java:args>
      </java:invoke-static>
    </on-error-continue>
</error-handler>
----

== See also

xref:4.1@mule-runtime::mule-error-concept.adoc[About the Mule Error]